name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        uses: mskelton/setup-yarn@v1
        with:
          cmd: install
      - name: Start Unit Test
        uses: mskelton/setup-yarn@v1
        with:
          cmd: test
